color = input("Enter a color: ")
plural_noun = input("Enter a plural_noun: ")
celebrity = input("Enter a celebrity: ")
print("Rose are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)
print("Do you to?")
